
version: "3.8"
   
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn api_cars.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db.prod

volumes:
  postgres_data: