FROM python:3.8.6-buster
WORKDIR /netguru
ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y netcat
COPY requirements.txt /netguru/
RUN pip install -r requirements.txt

# Copy project
COPY . .

ENTRYPOINT ["/netguru/entrypoint.prod.sh"]
